# Generated by Django 3.2.7 on 2021-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_operation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='balance',
            field=models.FloatField(default=121.25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='value',
            field=models.FloatField(),
        ),
    ]
