# Generated by Django 3.2.7 on 2021-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211007_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('Estacionar', 'Estacionar'), ('Compra de Créditos', 'Compra de Créditos'), ('Pagar NR', 'Pagar NR')], max_length=70),
        ),
        migrations.AlterField(
            model_name='operation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Pix', 'Pix')], max_length=70, null=True),
        ),
    ]
