# Generated by Django 3.2.7 on 2021-10-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211009_1442'),
        ('home', '0011_auto_20211009_1512'),
    ]

    operations = [
    ]
