# Generated by Django 3.2.7 on 2021-10-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211011_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
