# Generated by Django 3.2.7 on 2021-10-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211011_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='day_parked',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('Estacionar', 'Estacionar'), ('Compra de Créditos', 'Compra de Créditos')], max_length=70),
        ),
    ]
